//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 06:41:17 PM BST 
//


package com.halfords.connectors.sap.store6;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArticleStockLevels complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArticleStockLevels"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ArticleNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="QtyRequired" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="StoresStockLevels" type="{http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order}ArrayOfArticleStockLevels.StoreStockLevel" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArticleStockLevels", namespace = "http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order", propOrder = {
    "articleNumber",
    "qtyRequired",
    "storesStockLevels"
})
public class ArticleStockLevels {

    @XmlElementRef(name = "ArticleNumber", namespace = "http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order", type = JAXBElement.class, required = false)
    protected JAXBElement<String> articleNumber;
    @XmlElement(name = "QtyRequired")
    protected Integer qtyRequired;
    @XmlElementRef(name = "StoresStockLevels", namespace = "http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfArticleStockLevelsStoreStockLevel> storesStockLevels;

    /**
     * Gets the value of the articleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getArticleNumber() {
        return articleNumber;
    }

    /**
     * Sets the value of the articleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setArticleNumber(JAXBElement<String> value) {
        this.articleNumber = value;
    }

    /**
     * Gets the value of the qtyRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQtyRequired() {
        return qtyRequired;
    }

    /**
     * Sets the value of the qtyRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQtyRequired(Integer value) {
        this.qtyRequired = value;
    }

    /**
     * Gets the value of the storesStockLevels property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArticleStockLevelsStoreStockLevel }{@code >}
     *     
     */
    public JAXBElement<ArrayOfArticleStockLevelsStoreStockLevel> getStoresStockLevels() {
        return storesStockLevels;
    }

    /**
     * Sets the value of the storesStockLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArticleStockLevelsStoreStockLevel }{@code >}
     *     
     */
    public void setStoresStockLevels(JAXBElement<ArrayOfArticleStockLevelsStoreStockLevel> value) {
        this.storesStockLevels = value;
    }

}
