//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 06:41:17 PM BST 
//


package com.halfords.connectors.sap.store6;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AlloyWheel" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}AlloyWheelInfo" minOccurs="0"/&gt;
 *         &lt;element name="Article" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}ArticleInfo" minOccurs="0"/&gt;
 *         &lt;element name="BookingReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BuiltOrBoxed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Delivery" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}DeliveryInfo" minOccurs="0"/&gt;
 *         &lt;element name="DiscPriceInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ECP" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}ECPOrderInfo" minOccurs="0"/&gt;
 *         &lt;element name="EbayReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Fitment" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}FitmentInfo" minOccurs="0"/&gt;
 *         &lt;element name="FulfilmentMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LineCollectionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="LineNo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PersonalisationDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PersonalisationSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Pricing" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}PricingInfo" minOccurs="0"/&gt;
 *         &lt;element name="PromoLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Qty" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SapLineNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VRNno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="Wee" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}WEEEInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", propOrder = {
    "alloyWheel",
    "article",
    "bookingReference",
    "builtOrBoxed",
    "delivery",
    "discPriceInd",
    "ecp",
    "ebayReference",
    "fitment",
    "fulfilmentMethod",
    "lineCollectionDate",
    "lineNo",
    "personalisationDetails",
    "personalisationSKU",
    "pricing",
    "promoLine",
    "qty",
    "sku",
    "sapLineNo",
    "vrNno",
    "value",
    "wee"
})
public class Item {

    @XmlElementRef(name = "AlloyWheel", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AlloyWheelInfo> alloyWheel;
    @XmlElementRef(name = "Article", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ArticleInfo> article;
    @XmlElementRef(name = "BookingReference", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bookingReference;
    @XmlElementRef(name = "BuiltOrBoxed", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> builtOrBoxed;
    @XmlElementRef(name = "Delivery", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<DeliveryInfo> delivery;
    @XmlElementRef(name = "DiscPriceInd", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> discPriceInd;
    @XmlElementRef(name = "ECP", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ECPOrderInfo> ecp;
    @XmlElementRef(name = "EbayReference", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ebayReference;
    @XmlElementRef(name = "Fitment", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<FitmentInfo> fitment;
    @XmlElementRef(name = "FulfilmentMethod", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fulfilmentMethod;
    @XmlElement(name = "LineCollectionDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lineCollectionDate;
    @XmlElement(name = "LineNo")
    protected Integer lineNo;
    @XmlElementRef(name = "PersonalisationDetails", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> personalisationDetails;
    @XmlElementRef(name = "PersonalisationSKU", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> personalisationSKU;
    @XmlElementRef(name = "Pricing", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<PricingInfo> pricing;
    @XmlElementRef(name = "PromoLine", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> promoLine;
    @XmlElement(name = "Qty")
    protected Integer qty;
    @XmlElementRef(name = "SKU", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sku;
    @XmlElementRef(name = "SapLineNo", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sapLineNo;
    @XmlElementRef(name = "VRNno", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> vrNno;
    @XmlElement(name = "Value")
    protected BigDecimal value;
    @XmlElementRef(name = "Wee", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<WEEEInfo> wee;

    /**
     * Gets the value of the alloyWheel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AlloyWheelInfo }{@code >}
     *     
     */
    public JAXBElement<AlloyWheelInfo> getAlloyWheel() {
        return alloyWheel;
    }

    /**
     * Sets the value of the alloyWheel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AlloyWheelInfo }{@code >}
     *     
     */
    public void setAlloyWheel(JAXBElement<AlloyWheelInfo> value) {
        this.alloyWheel = value;
    }

    /**
     * Gets the value of the article property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArticleInfo }{@code >}
     *     
     */
    public JAXBElement<ArticleInfo> getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArticleInfo }{@code >}
     *     
     */
    public void setArticle(JAXBElement<ArticleInfo> value) {
        this.article = value;
    }

    /**
     * Gets the value of the bookingReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBookingReference() {
        return bookingReference;
    }

    /**
     * Sets the value of the bookingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBookingReference(JAXBElement<String> value) {
        this.bookingReference = value;
    }

    /**
     * Gets the value of the builtOrBoxed property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBuiltOrBoxed() {
        return builtOrBoxed;
    }

    /**
     * Sets the value of the builtOrBoxed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBuiltOrBoxed(JAXBElement<String> value) {
        this.builtOrBoxed = value;
    }

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DeliveryInfo }{@code >}
     *     
     */
    public JAXBElement<DeliveryInfo> getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DeliveryInfo }{@code >}
     *     
     */
    public void setDelivery(JAXBElement<DeliveryInfo> value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the discPriceInd property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDiscPriceInd() {
        return discPriceInd;
    }

    /**
     * Sets the value of the discPriceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDiscPriceInd(JAXBElement<String> value) {
        this.discPriceInd = value;
    }

    /**
     * Gets the value of the ecp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ECPOrderInfo }{@code >}
     *     
     */
    public JAXBElement<ECPOrderInfo> getECP() {
        return ecp;
    }

    /**
     * Sets the value of the ecp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ECPOrderInfo }{@code >}
     *     
     */
    public void setECP(JAXBElement<ECPOrderInfo> value) {
        this.ecp = value;
    }

    /**
     * Gets the value of the ebayReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEbayReference() {
        return ebayReference;
    }

    /**
     * Sets the value of the ebayReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEbayReference(JAXBElement<String> value) {
        this.ebayReference = value;
    }

    /**
     * Gets the value of the fitment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FitmentInfo }{@code >}
     *     
     */
    public JAXBElement<FitmentInfo> getFitment() {
        return fitment;
    }

    /**
     * Sets the value of the fitment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FitmentInfo }{@code >}
     *     
     */
    public void setFitment(JAXBElement<FitmentInfo> value) {
        this.fitment = value;
    }

    /**
     * Gets the value of the fulfilmentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFulfilmentMethod() {
        return fulfilmentMethod;
    }

    /**
     * Sets the value of the fulfilmentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFulfilmentMethod(JAXBElement<String> value) {
        this.fulfilmentMethod = value;
    }

    /**
     * Gets the value of the lineCollectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLineCollectionDate() {
        return lineCollectionDate;
    }

    /**
     * Sets the value of the lineCollectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLineCollectionDate(XMLGregorianCalendar value) {
        this.lineCollectionDate = value;
    }

    /**
     * Gets the value of the lineNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineNo() {
        return lineNo;
    }

    /**
     * Sets the value of the lineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineNo(Integer value) {
        this.lineNo = value;
    }

    /**
     * Gets the value of the personalisationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPersonalisationDetails() {
        return personalisationDetails;
    }

    /**
     * Sets the value of the personalisationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPersonalisationDetails(JAXBElement<String> value) {
        this.personalisationDetails = value;
    }

    /**
     * Gets the value of the personalisationSKU property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPersonalisationSKU() {
        return personalisationSKU;
    }

    /**
     * Sets the value of the personalisationSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPersonalisationSKU(JAXBElement<String> value) {
        this.personalisationSKU = value;
    }

    /**
     * Gets the value of the pricing property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PricingInfo }{@code >}
     *     
     */
    public JAXBElement<PricingInfo> getPricing() {
        return pricing;
    }

    /**
     * Sets the value of the pricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PricingInfo }{@code >}
     *     
     */
    public void setPricing(JAXBElement<PricingInfo> value) {
        this.pricing = value;
    }

    /**
     * Gets the value of the promoLine property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPromoLine() {
        return promoLine;
    }

    /**
     * Sets the value of the promoLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPromoLine(JAXBElement<String> value) {
        this.promoLine = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQty(Integer value) {
        this.qty = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSKU(JAXBElement<String> value) {
        this.sku = value;
    }

    /**
     * Gets the value of the sapLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSapLineNo() {
        return sapLineNo;
    }

    /**
     * Sets the value of the sapLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSapLineNo(JAXBElement<String> value) {
        this.sapLineNo = value;
    }

    /**
     * Gets the value of the vrNno property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVRNno() {
        return vrNno;
    }

    /**
     * Sets the value of the vrNno property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVRNno(JAXBElement<String> value) {
        this.vrNno = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the wee property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WEEEInfo }{@code >}
     *     
     */
    public JAXBElement<WEEEInfo> getWee() {
        return wee;
    }

    /**
     * Sets the value of the wee property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WEEEInfo }{@code >}
     *     
     */
    public void setWee(JAXBElement<WEEEInfo> value) {
        this.wee = value;
    }

}
