//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 06:41:17 PM BST 
//


package com.halfords.connectors.sap.store6;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricingInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CostPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="GBP" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}PriceStructure" minOccurs="0"/&gt;
 *         &lt;element name="IsPromoApplied" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ROI" type="{http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts}PriceStructure" minOccurs="0"/&gt;
 *         &lt;element name="VATCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingInfo", propOrder = {
    "costPrice",
    "gbp",
    "isPromoApplied",
    "roi",
    "vatCode"
})
public class PricingInfo {

    @XmlElement(name = "CostPrice")
    protected BigDecimal costPrice;
    @XmlElementRef(name = "GBP", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<PriceStructure> gbp;
    @XmlElement(name = "IsPromoApplied")
    protected Boolean isPromoApplied;
    @XmlElementRef(name = "ROI", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<PriceStructure> roi;
    @XmlElementRef(name = "VATCode", namespace = "http://schemas.datacontract.org/2004/07/HAL.Web.Order.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> vatCode;

    /**
     * Gets the value of the costPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * Sets the value of the costPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostPrice(BigDecimal value) {
        this.costPrice = value;
    }

    /**
     * Gets the value of the gbp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceStructure }{@code >}
     *     
     */
    public JAXBElement<PriceStructure> getGBP() {
        return gbp;
    }

    /**
     * Sets the value of the gbp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceStructure }{@code >}
     *     
     */
    public void setGBP(JAXBElement<PriceStructure> value) {
        this.gbp = value;
    }

    /**
     * Gets the value of the isPromoApplied property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPromoApplied() {
        return isPromoApplied;
    }

    /**
     * Sets the value of the isPromoApplied property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPromoApplied(Boolean value) {
        this.isPromoApplied = value;
    }

    /**
     * Gets the value of the roi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceStructure }{@code >}
     *     
     */
    public JAXBElement<PriceStructure> getROI() {
        return roi;
    }

    /**
     * Sets the value of the roi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceStructure }{@code >}
     *     
     */
    public void setROI(JAXBElement<PriceStructure> value) {
        this.roi = value;
    }

    /**
     * Gets the value of the vatCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVATCode() {
        return vatCode;
    }

    /**
     * Sets the value of the vatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVATCode(JAXBElement<String> value) {
        this.vatCode = value;
    }

}
