//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 06:41:17 PM BST 
//


package com.halfords.connectors.sap.store6;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StockLevelRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StockLevelRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ArticlesStockLevels" type="{http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order}ArrayOfArticleStockLevels" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StockLevelRequest", namespace = "http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order", propOrder = {
    "articlesStockLevels"
})
public class StockLevelRequest {

    @XmlElementRef(name = "ArticlesStockLevels", namespace = "http://schemas.datacontract.org/2004/07/HAL.IIS.BTEIntegration.Order", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfArticleStockLevels> articlesStockLevels;

    /**
     * Gets the value of the articlesStockLevels property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArticleStockLevels }{@code >}
     *     
     */
    public JAXBElement<ArrayOfArticleStockLevels> getArticlesStockLevels() {
        return articlesStockLevels;
    }

    /**
     * Sets the value of the articlesStockLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArticleStockLevels }{@code >}
     *     
     */
    public void setArticlesStockLevels(JAXBElement<ArrayOfArticleStockLevels> value) {
        this.articlesStockLevels = value;
    }

}
